allowBuilds:
  core-js: false
  electron: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - electron
  - esbuild
  - sharp
  - unrs-resolver
ignoredBuiltDependencies:
  - core-js
